Added ignoreList option
MadLittleMods/postcss-increase-specificity pull request #16
Opened 2018-01-17 20:12 UTC by IvanKalinin

Added an option that allows us to ignore certain selectors with increase of specificity

2018-02-04 20:38 UTC, MadLittleMods commented
@IvanKalinin Sorry for the delay. Any reason not to use `postcss-plugin-context`, example here, https://github.com/MadLittleMods/postcss-increase-specificity#only-apply-to-certain-sections-of-styles

Or you could use [`postcss-raw`](https://github.com/MadLittleMods/postcss-raw) to remove the selector while increasing the specificity.

```
var postcss = require('postcss');
var raw = require('postcss-raw');
var increaseSpecificity = require('postcss-increase-specificity');

var fs = require('fs');

var mycss = fs.readFileSync('input.css', 'utf8');

// Process your CSS with postcss-reverse-media
var output = postcss([
		raw.inspect(/*options*/),
		increaseSpecificity(/*options*/),
		raw.write(/*options*/)
                // ... your other plugins
	])
	.process(mycss)
	.css;

console.log(output);
```

wdyt?

2018-02-16 05:16 UTC, IvanKalinin commented
@MadLittleMods Sorry, now I missed your reply.
According to your README example `postcss-plugin-context` provides ability to increase specificity for certain section. But ignoreList does opposite thing. It exclude some sections (selectors from) for processing.
`postcss-raw` requires additional wrappers in existed stylesheets. So I'm not sure that those plugins fit in the need

2018-02-16 06:09 UTC, MadLittleMods requested changes
We also need to update the readme

2018-02-16 06:09 UTC, MadLittleMods commented on test/fixtures/ignore-list.css
> +
Let's change the selector to ignore, `.ignoreselector` so it's easier to understand

We also need to add a test for `.ignoreselector-notme`  (doesn't pass AFAICT)

2018-02-16 06:09 UTC, MadLittleMods commented on index.js
> +				var regEx = new RegExp(item.replace('.', '\\.') + '\\b', 'gi');
We should precompute these regexes outside of the `rule.selectors.map` loop.

---

Some small nits

 - `opts.ignoreList.some(function(ignoreItem) {`
 - `regEx -> `ingoreRe`

---

We should note in the docs that this doesn't handle complex ingore selectors.

ex.

 - Ignore `.foo.bar`
 - Selector: `.foo.QUX.bar` would still increase specificity even though it is technically under the `.foo.bar` scope

2018-02-16 06:12 UTC, MadLittleMods commented
@IvanKalinin The alternative solutions do involve more markup but it may also be easier to understand how it works if the ignore context is in the CSS.

Another solution could be to ignore any rule with a comment above `// ignore-postcss-increase-specificity`. Just a thought.

2018-05-31 17:06 UTC, MadLittleMods commented
Closing in favor of inline comment ignore solution, https://github.com/MadLittleMods/postcss-increase-specificity/issues/17

2018-05-31 17:06 UTC, closed without merging