Feat/more specificity
MadLittleMods/postcss-increase-specificity pull request #9
Opened 2017-04-25 15:42 UTC by iamstarkov

here i am with a pr

2017-04-25 17:20 UTC, iamstarkov commented on index.js
> +					(/#(?!\\)/).test(rule.selector) ||
this thing needed to be changed, because otherwise original regexp catches `#` in `:not(#\20)` and doesnt add `!important`

2017-04-26 06:45 UTC, iamstarkov commented
so, @MadLittleMods what do you think?

2017-05-18 15:48 UTC, iamstarkov commented
@MadLittleMods is something wrong?

2017-05-18 16:02 UTC, MadLittleMods commented on package.json
> +    "tdd": "mocha --watch"
We could use `npm test -- --watch` instead

2017-05-18 16:06 UTC, MadLittleMods commented
Sorry for the delay @iamstarkov 😢 

Reviewing now

2017-05-18 16:27 UTC, MadLittleMods commented on index.js
> +					selector === ':not(#\\20)' ||
We should put this back to `:root`. `:not(#\\20)` would be covered by the last case `selector === opts.stackableRoot`

2017-05-18 16:27 UTC, MadLittleMods requested changes

2017-05-18 16:27 UTC, MadLittleMods commented on index.js
> +					selector === ':not(#\\20)' ||
We should put this back to `:root`. `:not(#\\20)` would be covered by the last case `selector === opts.stackableRoot`

2017-05-18 16:29 UTC, MadLittleMods commented on CHANGELOG.md
> +[#9]: https://github.com/MadLittleMods/postcss-increase-specificity/pull/9
I prefer inline linking vs references. Seems fine to keep it for now as it will be changed in the release.

2017-05-18 16:31 UTC, MadLittleMods commented
@iamstarkov I'll take care of the remaining points (no need for a further fix commit).

2017-05-18 16:42 UTC, MadLittleMods commented
Merged via https://github.com/MadLittleMods/postcss-increase-specificity/pull/10

Thanks @iamstarkov 💓 😺 

Appreciate the ping again to take a look. This was sitting in my inbox for too long.

2017-05-18 16:42 UTC, closed without merging

2017-05-18 16:51 UTC, MadLittleMods commented
Published in [`postcss-increase-specificity@0.4.0`](https://github.com/MadLittleMods/postcss-increase-specificity/blob/master/CHANGELOG.md#v040---2017-5-18), https://www.npmjs.com/package/postcss-increase-specificity

2017-05-19 10:28 UTC, iamstarkov commented
@MadLittleMods thank you